### ISSUE TITLE
Correções Necessárias

### ISSUE THREAD

**Issue by Lucas-Munhoz** [Lucas-Munhoz/PresenceList#12]
**Detalhes apontados pelo professor que precisam de correção:**  
- Gerenciamento de ISSUES.
- Definir um banco de dados próprio para testes.
- Implementar testes de FrontEnd.

**Comment by Lucas-Munhoz** [comment]
Gerenciamento de ISSUES concluída, para mais informações, verificar as ISSUES #4 e #5 e seus respectivos comentários.

**Comment by Lucas-Munhoz** [comment]
Banco de dados de testes implementado no commit aa76e33 da branch Sprint1/Correcoes.

**Comment by Lucas-Munhoz** [comment]
Testes de FRONTEND da tela Cadastro de Professores, foram implementados na branch #13

**Comment by MatsuJR** [comment]
Testes de frontend para as telas de redefinição de senha e login de professor, foram implementadas na branch #14
